In [1]:
import numpy as np
import pandas as pd

   #  Attribute                     Domain
   -- -----------------------------------------
   1. Sample code number            id number
   2. Clump Thickness               1 - 10
   3. Uniformity of Cell Size       1 - 10
   4. Uniformity of Cell Shape      1 - 10
   5. Marginal Adhesion             1 - 10
   6. Single Epithelial Cell Size   1 - 10
   7. Bare Nuclei                   1 - 10
   8. Bland Chromatin               1 - 10
   9. Normal Nucleoli               1 - 10
  10. Mitoses                       1 - 10
  11. Class:                        (2 for benign, 4 for malignant)

In [2]:
df=pd.read_csv("breast-cancer-wisconsin.data")
df.columns=['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape',
'Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin ','Normal Nucleoli','Mitoses','Class:']

In [3]:
df

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class:
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           698 non-null    int64
 1   Clump Thickness              698 non-null    int64
 2   Uniformity of Cell Size      698 non-null    int64
 3   Uniformity of Cell Shape     698 non-null    int64
 4   Marginal Adhesion            698 non-null    int64
 5   Single Epithelial Cell Size  698 non-null    int64
 6   Bare Nuclei                  698 non-null    object
 7   Bland Chromatin              698 non-null    int64
 8   Normal Nucleoli              698 non-null    int64
 9   Mitoses                      698 non-null    int64
 10  Class:                       698 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB

In [4]:
df["Bare Nuclei"].replace("?",1,inplace =True)

In [20]:
df["Bare Nuclei"]=df["Bare Nuclei"].astype('int64')

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier


from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

from sklearn.preprocessing import StandardScaler 

models =[("LogisticRegression",LogisticRegression()),("KNeighborsClassifier",KNeighborsClassifier()),("DecisionTreeClassifier",DecisionTreeClassifier()),("RandomForestClassifier",RandomForestClassifier()),("AdaBoostClassifier",AdaBoostClassifier()),("XGBClassifier",XGBClassifier(objective="binary:logistic", random_state=42))]

In [14]:
from sklearn.model_selection import train_test_split

In [26]:
df['Class:'].replace({2: 0, 4: 1},inplace=True)

In [33]:
x=df.drop(['Class:','Sample code number'],axis=1)

y=df['Class:']
x_tr,x_ts,y_tr,y_ts =train_test_split(x,y,test_size=0.3,random_state=34)

In [34]:
for name,model in models:
    model.fit(x_tr,y_tr)
    pred =model.predict(x_ts)
    a=accuracy_score(y_ts,pred)
    print(f"accuracy score:: {name} ::{a} \n")
    print()

accuracy score:: LogisticRegression ::0.9571428571428572


accuracy score:: KNeighborsClassifier ::0.9714285714285714


accuracy score:: DecisionTreeClassifier ::0.9333333333333333


accuracy score:: RandomForestClassifier ::0.9619047619047619


accuracy score:: AdaBoostClassifier ::0.9619047619047619


accuracy score:: XGBClassifier ::0.9571428571428572